### PR TITLE
Implement SoraEditor

### PR DESCRIPTION
**Pull request by khaled-0**
Although there are still some issues which i currently don't know how to deal with.
1. Call ``updateTitle`` method when text is edited (How to detect??)
2. Update toolbar color scheme on dark/light mode toggle

For 2nd issue, Saving the text state isn't possible using bundle because the max bundle size is only around 500kb.
But even with these issues, it's still a great text editor compared to current one.
If you want any changes then please say so.

And Thanks for this wonderful project.

image
image

### CODE REVIEW

**Comment by khaled-0** [comment]
https://github.com/zhanghai/MaterialFiles/issues/878

**Comment by khaled-0** [comment]
@zhanghai I know you're busy but please review this when you have time

**Comment by Aleksanaa** [comment]
Please also consider to selectively use monospace font

**Comment by brian6932** [comment]
Can someone rebase this PR and fix the aforementioned bugs please, line counts are very essential and there really isn't another Android sftp file manager that works as well as this one or sshfs mounting on Android 14.

**Comment by khaled-0** [comment]
I'm wanting to give this another shot.
hopefully before Christmas idk.

**Pull request closed without merging**
