### PR TITLE
[Fix] Ignore ssh host key verify.

### PR DESCRIPTION
**Pull request by sunjw**
First of all, thank you for your interest in help improving this project! However, I normally won't accept PRs for this project because I'm currently the only copyright owner for it (except for translations and maybe my company), which I think would be a nice thing to keep along. On the other hand, forcing people to give up their copyright to me is both awkward and legally-complex. So if you have any suggestions for an improvement, please feel free to comment on existing issues or open a new one!

A very nice and useful file manager on Android. Just want to say ssh connection and file copy/paste over ssh is quit broken.

### CODE REVIEW

**Comment by zhanghai** [comment]
Thanks for pointing this out! I haven't actually tested the new SFTP functionality yet. Your suggestion makes sense and I'll implement it in my code.

**Comment by zhanghai** [comment]
Could you help check if SFTP works after ba1b4cf?

**Comment by sunjw** [comment]
ssh connection is OK, but I found file copy from phone to ssh is broken, keep sending data and progress bar keep 0.

**Comment by zhanghai** [comment]
Is copying from SFTP to phone working? And what about other things like file info, or rename?

**Comment by sunjw** [comment]
Just do some very very simple test.
> Is copying from SFTP to phone working?
Looks like it works properly.
> And what about other things like file info, opening a remote file and rename?
Looks like it works properly.

**Comment by zhanghai** [comment]
Glad that everything else worked out of the box - but the copy to remote case is still misteriously broken. Seems I'll have to set up a writable SFTP server locally to test.

**Comment by zhanghai** [comment]
Fixed in e7eeebe.

**Pull request closed without merging**
