### PR TITLE
Updated ru (Russian) translation

### PR DESCRIPTION
**Pull request by ferhadnecef**

### CODE REVIEW

**Comment by zhanghai** [comment]
Hi, thanks for the PR! However this seems to be based on a wrong branch and translation for this project is handled on Transifex, so I'll have to close this PR. Please help Russian translation at https://www.transifex.com/zhanghai/MaterialFiles/language/ru/ (if you like).

**Comment by enessgokalp** [comment]
I can translate to turkish

**Comment by ferhadnecef** [comment]
This is very good! Thanks) 

7 дек. 2019 г. 12:59:15 enessgokalp <notifications@github.com>:

**Comment by enessgokalp** [comment]
How can I do ferhadnecef

**Comment by ferhadnecef** [comment]
It is necessary to ban the addition of the Turkish language on the project page. 

7 дек. 2019 г. 17:17:08 enessgokalp <notifications@github.com>:

**Comment by enessgokalp** [comment]
Why @ferhadnecef

**Pull request closed without merging**
