### PR TITLE
use storageprovider flags

### PR DESCRIPTION
**Pull request by jmue**
Evaluate storageprovider flags for COPY/MOVE/DELETE operations. With this commit these methods are only called if the storageprovider declares supporting them. Feel free to include/modify this pull request.

Signed-off-by: Jens Mueller <tschenser@gmx.de>

### CODE REVIEW

**Comment by zhanghai** [comment]
This requires a lot of extra IPCs for each file operation, so it is far from desirable for performance.

**Comment by jmue** [comment]
I get your concerns. But let me add two points here:

- aren't these flags exists to get queried?
- some document-provider may not support copy | move | remove operations, but your are still trying to call these methods. In this case an exception is created on the storage-provider side. This exception is caught on your side and the fallback comes into place. Aren't that more ipcs than querying these flags?

**Comment by zhanghai** [comment]
Any data on how many `DocumentProvider` supports or doesn't support these operations?
Meanwhile, trying first and falling back is also just one extra IPC, whereas if the provider does support it, the initial query for metadata becomes a penalty.

**Comment by jmue** [comment]
No, I do not have this data.

From my point of view, the exact number of ipcs doesn't matter here (I mean we're talking about a single ipc in case of user triggered action, which is 2 taps away at best). Instead network round trips do so, but they also don't vote for or against this pr.

From my first look at the design, not considering the existing feature flags and having hard coded lists looks odd, but from an exceptional programmer's point of view,  that's okay. So I'm fine with closig this pr.

**Comment by zhanghai** [comment]
> From my point of view, the exact number of ipcs doesn't matter here (I mean we're talking about a single ipc in case of user triggered action, which is 2 taps away at best). Instead network round trips do so, but they also don't vote for or against this pr.

In the case of bulk file operations, e.g. recursively deleting a folder with a lot of files, the number of IPCs for each single operation will matter for performance.

> From my first look at the design, not considering the existing feature flags and having hard coded lists looks odd, but from an exceptional programmer's point of view, that's okay. So I'm fine with closig this pr.

Not sure what you meant by "exceptional programmer". But anyway, that API design is useful when the caller has already retrived the file information for display and need to do something with that exact file based on user interaction on the file. However due to our abstraction here, and also in the case of bulk operations, having to retrieve the flags beforehand means an extra IPC and it seems to be less performant than simplying trying the support first.

**Comment by jmue** [comment]
> In the case of bulk file operations, e.g. recursively deleting a folder with a lot of files, the number of IPCs for each single operation will matter for performance.
Uh, is that the case? I expected the flags would be evaluated once for that folder, not for every item that it contains.

> Not sure what you meant by "exceptional programmer". But anyway, that API design is useful when the caller has already retrived the file information for display and need to do something with that exact file based on user interaction on the file. However due to our abstraction here, and also in the case of bulk operations, having to retrieve the flags beforehand means an extra IPC and it seems to be less performant than simplying trying the support first.
I'm mainly familiar with programming languages not throwing exceptions. As they are part of the usual control flow here that's perfectly fine.

**Comment by zhanghai** [comment]
> Uh, is that the case? I expected the flags would be evaluated once for that folder, not for every item that it contains.

Every file has a flags column and technically the provider is free to return whatever value for different files. And it may also happen in reality e.g. for a folder containing a mount point.

> I'm mainly familiar with programming languages not throwing exceptions. As they are part of the usual control flow here that's perfectly fine.

I see. Yes normally people are discouraged from using exceptions for control flow, and there are indeed performance impact from using exceptions. However, an additional IPC is still much slower than that (I assume at least by an order of magnitude) so using exception in this case should be fine.

**Comment by jmue** [comment]
> Every file has a flags column and technically the provider is free to return whatever value for different files. And it may also happen in reality e.g. for a folder containing a mount point.

Indeed, you're right.

Thank you for providing Material files!

**Pull request closed without merging**
